In [1]:
import numpy as np

In [2]:
import pandas as pd

1) Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.
2) Find common elements between A and B. [Hint: Intersection of two sets]
3) Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]
4) Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

1) Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [6]:
A = np.arange(1,11)
B = np.random.randint(1,11,10)

In [10]:
C = np.vstack((A,B))
C

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  4,  2,  6,  2,  8,  5,  1,  9,  1]])

In [12]:
D = np.hstack((A,B))
D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  3,  4,  2,  6,  2,  8,  5,
        1,  9,  1])

2) Find common elements between A and B. [Hint: Intersection of two sets]

In [17]:
common = np.isin(A,B)
print(common)
print(A[common])

[ True  True  True  True  True  True False  True  True False]
[1 2 3 4 5 6 8 9]


3) Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [27]:
A[(A >= 5) & (A <= 8)]

array([5, 6, 7, 8])

4) Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [30]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

iris_2d[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [33]:
mask = (iris_2d[:,2] > 1.5) & (iris_2d[:,0] < 5.0)
iris_2d[mask]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])